Add file2.rb
tavisca-tkatyal/Assignment pull request #1
Opened 2019-06-26 12:40 UTC by tavisca-tkatyal

@tavisca-vtripathi

2019-06-27 04:54 UTC, tavisca-vtripathi requested changes

2019-06-27 04:54 UTC, tavisca-vtripathi commented on lib/file2.rb
> +require 'pathname'
Put the logic in a method

2019-06-27 13:34 UTC, tavisca-tkatyal commented
@tavisca-vtripathi 
method add in file2.rb

2019-06-29 13:47 UTC, tavisca-vtripathi requested changes

2019-06-29 13:47 UTC, tavisca-vtripathi commented on lib/file2.rb
> +puts "Hello user, Please Input the folder name"
Put user input as well in a method and do the calling.

2019-06-29 14:39 UTC, tavisca-tkatyal commented
done the suggested Changes.
@tavisca-vtripathi

2019-06-29 14:40 UTC, tavisca-vtripathi approved these changes

2019-07-02 12:52 UTC, closed without merging